import { LightingConfig, LightingPreset, MaterialSpec } from './types';

export const LIGHTING_PRESETS: Record<LightingPreset, LightingConfig> = {
  midnight: {
    name: 'midnight',
    label: 'Midnight Luminescence',
    ambientColor: '#0f172a',
    ambientIntensity: 0.9,
    directionalColor: '#93c5fd',
    directionalIntensity: 1.4,
    directionalPos: [6, 8, 4],
    screenGlowColor: '#10b981',
    screenGlowIntensity: 4.5,
    lampGlowColor: '#f97316',
    lampGlowIntensity: 2.2,
    bgHex: '#080a0f',
  },
  sunset: {
    name: 'sunset',
    label: 'Golden Hour Ray',
    ambientColor: '#451a03',
    ambientIntensity: 1.2,
    directionalColor: '#fbbf24',
    directionalIntensity: 2.8,
    directionalPos: [7, 4, 3],
    screenGlowColor: '#34d399',
    screenGlowIntensity: 2.0,
    lampGlowColor: '#ea580c',
    lampGlowIntensity: 1.5,
    bgHex: '#120f0d',
  },
  studio: {
    name: 'studio',
    label: 'Architectural Neutral',
    ambientColor: '#f8fafc',
    ambientIntensity: 1.6,
    directionalColor: '#ffffff',
    directionalIntensity: 2.0,
    directionalPos: [5, 9, 5],
    screenGlowColor: '#10b981',
    screenGlowIntensity: 2.0,
    lampGlowColor: '#f59e0b',
    lampGlowIntensity: 1.0,
    bgHex: '#0e1117',
  },
  cyber: {
    name: 'cyber',
    label: 'Tokyo Noir',
    ambientColor: '#1e1b4b',
    ambientIntensity: 0.7,
    directionalColor: '#06b6d4',
    directionalIntensity: 1.8,
    directionalPos: [-4, 7, 5],
    screenGlowColor: '#10b981',
    screenGlowIntensity: 5.5,
    lampGlowColor: '#ec4899',
    lampGlowIntensity: 3.0,
    bgHex: '#07070c',
  },
};

export const MATERIAL_SPECS: MaterialSpec[] = [
  {
    id: 'GREEN EMIT',
    name: 'Emerald Phosphor Terminal',
    code: 'GREEN EMIT',
    color: '#10b981',
    type: 'Emissive',
    roughness: 0.1,
    description: 'Active OLED pixel matrix radiating 520nm monochromatic green emission across the desk surface.',
    emissiveIntensity: 3.5,
  },
  {
    id: 'EMISSION',
    name: 'Interface Core Glow',
    code: 'EMISSION',
    color: '#38bdf8',
    type: 'Emissive',
    roughness: 0.15,
    description: 'Dynamic backlighting unit delivering soft ambient blue tint to the spatial chamber.',
    emissiveIntensity: 2.2,
  },
  {
    id: 'BEDSHEET',
    name: 'Brushed Belgian Linen',
    code: 'BEDSHEET',
    color: '#cbd5e1',
    type: 'Diffuse',
    roughness: 0.88,
    description: 'Tactile, non-specular natural textile drape with organic micro-creases and diffuse light absorption.',
  },
  {
    id: 'ORANGE',
    name: 'Filament Incandescence',
    code: 'ORANGE',
    color: '#f97316',
    type: 'Emissive',
    roughness: 0.3,
    description: '2700K tungsten amber light emission casting warm radial shadows across the nightstand.',
    emissiveIntensity: 1.8,
  },
  {
    id: 'FLOOR.001',
    name: 'Volcanic Basalt Plinth',
    code: 'FLOOR.001',
    color: '#1e232d',
    type: 'Architectural',
    roughness: 0.45,
    description: 'Deep charcoal foundation slab featuring subtle anisotropic brushing and contact shadow retention.',
  },
  {
    id: 'WALL',
    name: 'Matte Mineral Concrete',
    code: 'WALL',
    color: '#333842',
    type: 'Architectural',
    roughness: 0.82,
    description: 'Micro-cement vertical boundary calibrated for gentle gradient falloffs and acoustic dampening.',
  },
  {
    id: 'ROCK1',
    name: 'Sculptural River Stones',
    code: 'ROCK1 / 2 / 3',
    color: '#64748b',
    type: 'Natural',
    roughness: 0.9,
    description: 'Curated organic river pebbles providing zen spatial contrast against rectilinear surfaces.',
  },
  {
    id: 'BLUE',
    name: 'Ultramarine Ergonomic Mesh',
    code: 'BLUE',
    color: '#2563eb',
    type: 'Diffuse',
    roughness: 0.65,
    description: 'High-tensile suspension polymer contouring the task chair seating module.',
  },
];
